package simtk.openmm;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class OpenMM_Vec3 extends Structure {
    public double x;
    public double y;
    public double z;

    public OpenMM_Vec3() {
        super();
    }

    protected List<?> getFieldOrder() {
        return Arrays.asList("x", "y", "z");
    }

    public OpenMM_Vec3(double x, double y, double z) {
        super();
        this.x = x;
        this.y = y;
        this.z = z;
    }

    public OpenMM_Vec3(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends OpenMM_Vec3 implements Structure.ByReference {

    }

    ;

    public static class ByValue extends OpenMM_Vec3 implements Structure.ByValue {

    }

    ;
}
